#!/bin/bash
# extract current branch name
BRANCH=$(git name-rev HEAD 2> /dev/null | awk "{ print \$2 }")
# get name of the most top folder of current directory, used for the
# output filename
ARCHIVE_NAME=$(basename $(pwd))
# get a version string, so archives will not be overwritten when creating
# many of the,
VERSION=$(git describe --always --long)
# if not on master append branch name into the filename
if [ "$BRANCH" = "master" ]; then
	FILENAME=$ARCHIVE_NAME.$VERSION.zip
else
	FILENAME=$ARCHIVE_NAME.$VERSION.$BRANCH.zip
fi
# building archive
git archive --format zip --output $(pwd)/$FILENAME $BRANCH