#!/bin/bash
BRANCH=$(git name-rev HEAD 2> /dev/null | awk "{ print \$2 }")
ARCHIVE_NAME=$(basename $(pwd))
VERSION=$(git describe --always --long)
if [ "$BRANCH" = "master" ]; then
	FILENAME=$ARCHIVE_NAME.$VERSION.zip
else
	FILENAME=$ARCHIVE_NAME.$VERSION.$BRANCH.zip
fi
echo git archive --format zip --output $(pwd)/$FILENAME $BRANCH